{% set name = "tvm-py" %}
{% set version = "0.8.0" %}
{% set proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/incubator-tvm/archive/v{{ version }}.tar.gz
  sha256: d950c5d159c1345d0727dfb3cabb456e6947a8cb80519feaeed8e0b35e6e913e

build:
  number: 0
  script:
    - cd python
    - {{ PYTHON }} setup.py install -vv
  skip: true  # [win]
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ proc_type }}  # [cuda_compiler_version == "None"]
  string: py{{ CONDA_PY }}{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ proc_type }}  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('cxx') }}  # [not osx]
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
  host:
    - libtvm =={{ version }}=*{{ proc_type }}*
    - python
    - cython
    - numpy
    - setuptools
    - scipy
    - psutil
    - decorator
    - attrs
    - typed-ast
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - psutil
    - decorator
    - attrs
    - typed-ast
    - libtvm =={{ version }}=*{{ proc_type }}*
    - llvmdev ==13
    - __cuda  # [cuda_compiler_version != "None"]

test:
  imports:
    - tvm
  requires:
   - pip
   - pytest
  source_files:
    - tests
  commands:
   - pip check
   - python -m pytest -v tests/python/all-platform-minimal-test
   - python -m pytest -v tests/python/unittest

about:
  home: https://tvm.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Open Deep Learning Compiler Stack
  description: |
    Apache TVM (incubating) is a compiler stack for deep learning systems.
    It is designed to close the gap between the productivity-focused deep
    learning frameworks, and the performance- and efficiency-focused hardware
    backends. TVM works with deep learning frameworks to provide end to end
    compilation to different backends.
  doc_url: https://tvm.apache.org/docs/
  dev_url: https://github.com/apache/incubator-tvm

extra:
  recipe-maintainers:
    - marcelotrevisani
