{% set name = "tvm-py" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/incubator-tvm/archive/v{{ version }}.tar.gz
  sha256: 84d825f25c9cfc7cf76359c41d4cd6a6dd53fd247f6f280c45268ce6835d2a10

build:
  number: 2
  script:
    - cd python
    - {{ PYTHON }} setup.py install -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - libtvm {{ version }}
    - python
    - cython
    - numpy
    - setuptools
    - scipy
    - psutil
    - decorator
    - attrs
    - typed-ast
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - psutil
    - decorator
    - attrs
    - typed-ast
    - libtvm {{ version }}

test:
  imports:
    - tvm

about:
  home: https://tvm.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Open Deep Learning Compiler Stack
  description: |
    Apache TVM (incubating) is a compiler stack for deep learning systems.
    It is designed to close the gap between the productivity-focused deep
    learning frameworks, and the performance- and efficiency-focused hardware
    backends. TVM works with deep learning frameworks to provide end to end
    compilation to different backends.
  doc_url: https://tvm.apache.org/docs/
  dev_url: https://github.com/apache/incubator-tvm

extra:
  recipe-maintainers:
    - marcelotrevisani
