bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
azure:
  settings_osx:
    pool:
      vmImage: macOS-11
conda_build:
  pkg_format: '2'
test: native_and_emulated
